import pkg from '../../package.json';

export const themeConfig = [
  {
    option: 'Default',
    value: {
      theme: 'charcoal',
      type: 'dark',
      settingsContainerColor: '#252525',
      navItemActive: '#f3f4f6',
      settingsSearchBar: '#1a1a1a',
      settingsPanelItemBackgroundColor: '#2e2e2e',
      settingsDropdownColor: '#101010',
      siteTextColor: '#d4d4d4',
      bgDesignColor: '37, 37, 37',
      glowWrapperColor: '255, 255, 255',
      switchColor: '#1f1f1f',
      switchEnabledColor: '#3b3b3b',
      bgColor: '#050505',
      quickModalBgColor: '#1c1c1c',
      paginationTextColor: '#c9c9c9',
      paginationBorderColor: '#ffffff1c',
      paginationBgColor: '#101010',
      paginationSelectedColor: '#858585',
      themeName: 'charcoalTheme',
      tabColor: "#141414",
      tabOutline: "#2a2a2a",
      barColor: "#0a0a0a",
      tabBarColor: "#050505",
      omninputColor: "#0505058f",
      menuColor: "#161616"
    },
  },
  {
    option: 'Midnight',
    value: {
      theme: 'default',
      type: 'dark',
      settingsContainerColor: '#18283e',
      navItemActive: '#c1d4f1',
      settingsSearchBar: '#3c475a',
      settingsPanelItemBackgroundColor: '#405a77',
      settingsDropdownColor: '#162337',
      siteTextColor: '#a0b0c8',
      bgDesignColor: '66, 69, 73',
      glowWrapperColor: '255, 255, 255',
      switchColor: '#ffffff1a',
      switchEnabledColor: '#4c6c91',
      bgColor: '#111827',
      quickModalBgColor: '#252f3e',
      paginationTextColor: '#9baec8',
      paginationBorderColor: '#ffffff1c',
      paginationBgColor: '#141d2b',
      paginationSelectedColor: '#75b3e8',
      themeName: 'defaultTheme',
      tabColor: "#111e2fb0",
      tabOutline: "#344646",
      barColor: "#09121e",
      tabBarColor: "#070e15",
      omninputColor: "#06080d8f",
      menuColor: "#1a252f"
    },
  },
  {
    option: 'Mocha',
    value: {
      theme: 'mocha',
      type: 'dark',
      settingsContainerColor: '#312222',
      navItemActive: '#fdedea',
      settingsSearchBar: '#312929',
      settingsPanelItemBackgroundColor: '#3d2a2a',
      settingsDropdownColor: '#291c1c',
      siteTextColor: '#c7bab8',
      bgDesignColor: '65, 47, 47',
      glowWrapperColor: '255, 255, 255',
      switchColor: '#463131',
      switchEnabledColor: '#7c5f5f',
      bgColor: '#1a1514',
      quickModalBgColor: '#362c2c',
      paginationTextColor: '#c3b6b6',
      paginationBorderColor: '#ffffff1c',
      paginationBgColor: '#231b15',
      paginationSelectedColor: '#956f6f',
      themeName: 'mochaTheme',
      tabColor: "#221a1a",
      tabOutline: "#3e3b3b",
      barColor: "#221a1a",
      tabBarColor: "#151313",
      omninputColor: "#1714148f",
      menuColor: "#282323"
    },
  },
  {
    option: 'Forest',
    value: {
      theme: 'forest',
      type: 'dark',
      settingsContainerColor: '#17281f',
      navItemActive: '#d4f3e1',
      settingsSearchBar: '#274233',
      settingsPanelItemBackgroundColor: '#315b45',
      settingsDropdownColor: '#15261c',
      siteTextColor: '#bfe5cf',
      bgDesignColor: '46, 66, 54',
      glowWrapperColor: '232, 255, 243',
      switchColor: '#375644',
      switchEnabledColor: '#3f7a5a',
      bgColor: '#0c1711',
      quickModalBgColor: '#15261c',
      paginationTextColor: '#cbe9cf',
      paginationBorderColor: '#ffffff1c',
      paginationBgColor: '#1d2d22',
      paginationSelectedColor: '#7ca387c4',
      themeName: 'forestTheme',
      tabColor: "#162218",
      tabOutline: "#2d3e28",
      barColor: "#162218",
      tabBarColor: "#131513",
      omninputColor: "#1714148f",
      menuColor: "#1d221d"
    },
  },
  {
    option: 'Dark',
    value: {
      theme: 'dark',
      type: 'dark',
      settingsContainerColor: '#18181c',
      navItemActive: '#f3f4f6',
      settingsSearchBar: '#1f1f23',
      settingsPanelItemBackgroundColor: '#2e2e34',
      settingsDropdownColor: '#151519',
      siteTextColor: '#fff',
      bgDesignColor: '73, 73, 73',
      glowWrapperColor: '255, 255, 255',
      switchColor: '#1f1f23',
      switchEnabledColor: '#3b3b44',
      bgColor: '#0b0b0e',
      quickModalBgColor: '#2d2d30',
      paginationTextColor: '#c9c9c9',
      paginationBorderColor: '#ffffff1c',
      paginationBgColor: '#1a1a1a',
      paginationSelectedColor: '#858585',
      themeName: 'darkTheme',
      tabColor: "#1a1a1a",
      tabOutline: "#353535",
      barColor: "#191a19",
      tabBarColor: "#0d0d0d",
      omninputColor: "#0b0a0a8f",
      menuColor: "#1c1c1c"
    },
  },
  {
    option: 'Stellar',
    value: {
      theme: 'stellar',
      type: 'dark',
      settingsContainerColor: '#141620',
      navItemActive: '#9db4ff',
      settingsSearchBar: '#232538',
      settingsPanelItemBackgroundColor: '#2d2f44',
      settingsDropdownColor: '#181a26',
      siteTextColor: '#d6daff',
      bgDesignColor: '127, 127, 127',
      glowWrapperColor: '136, 169, 255',
      switchColor: '#25273a',
      switchEnabledColor: '#5b6eff',
      bgColor: '#0b0c14',
      quickModalBgColor: '#181a28',
      paginationTextColor: '#c9cdf0',
      paginationBorderColor: '#ffffff1c',
      paginationBgColor: '#141620',
      paginationSelectedColor: '#8f9bd6',
      themeName: 'stellarTheme',
      tabColor: "#141620",
      tabOutline: "#2b2e44",
      barColor: "#0f1119",
      tabBarColor: "#0b0c14",
      omninputColor: "#0b0c148f",
      menuColor: "#161927"
    },
  },
];

export const meta = [
  {
    option: 'Default',
    value: { tabName: 'DogeUB', tabIcon: '/favicon.ico' },
  },
  {
    option: 'Blank',
    value: { tabName: 'New Tab', tabIcon: '' },
  },
];

export const appsPerPageConfig = [
  { option: '10', value: { itemsPerPage: 10 } },
  { option: '15', value: { itemsPerPage: 15 } },
  { option: '20', value: { itemsPerPage: 20 } },
  { option: '30', value: { itemsPerPage: 30 } },
  { option: 'All', value: { itemsPerPage: Infinity } },
];

export const navScaleConfig = [
  { option: '0.8x', value: { navScale: 0.8 } },
  { option: '0.9x', value: { navScale: 0.9 } },
  { option: '0.95x', value: { navScale: 0.95 } },
  { option: '1x (Default)', value: { navScale: 1 } },
  { option: '1.1x', value: { navScale: 1.1 } },
  { option: '1.2x', value: { navScale: 1.2 } },
];

export const searchConfig = [
  { option: 'Google', value: { engine: 'https://www.google.com/search?q=' } },
  { option: 'Bing', value: { engine: 'https://www.bing.com/search?q=' } },
  { option: 'DuckDuckGo', value: { engine: 'https://duckduckgo.com/?q=' } },
  { option: 'Brave', value: { engine: 'https://search.brave.com/search?q=' } },
];

export const prConfig = [
  { option: 'Automatic', value: { prType: 'auto' } },
  { option: 'Ultraviolet', value: { prType: 'uv' } },
  { option: 'Scramjet', value: { prType: 'scr' } },
];

export const designConfig = [
  {
    option: 'None',
    value: {
      bgDesign: 'None',
      getCSS: () => 'none',
    },
  },
  {
    option: 'Grid',
    value: {
      bgDesign: 'Grid',
      getCSS: (c) =>
        `linear-gradient(rgba(${c}, 0.15) 1px, transparent 1px), linear-gradient(90deg, rgba(${c}, 0.15) 1px, transparent 1px)`,
    },
  },
  {
    option: 'Dots',
    value: {
      bgDesign: 'Dots',
      getCSS: (c) => `radial-gradient(rgba(${c}, 0.3) 1px, transparent 1px)`,
    },
  },
];
